name: Bug
description: 反馈关于订阅链接的错误
title: "[Bug]"
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        请简练，概括的提出你的问题并写到上方的输入框内( ͡° ͜ʖ ͡°)
  - type: input
    id: bug-url
    attributes:
      label: 出现问题的订阅链接
      description: 告诉我你使用的哪个订阅链接出现问题了🤔（包括旧的订阅链接）
      placeholder: https://openit.ml/example
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - SS
        - 魔改ss
        - Matsuri
        - SagerNet
        - Quantumult X
        - Shadowrocket
        - Surge / Surfboard
        - v2rayN / v2rayNG / Qv2ray
        - Clash for Windows / Clash for Android / ClashX
        - 路由器
    validations:
      required: true
  - type: input
    id: bug-detail
    attributes:
      label: 复现方式
      description: 如果可以，请描述如何复现你的问题（可上传照片和文件）
      placeholder: 
    validations:
      required: true
