blank_issues_enabled: false
contact_links:
  - name: Openit Support
    url: https://t.me/yusteven
    about: 获得关于节点 / 订阅使用方面的支持 Telegram 有24h的人工客服💁‍♂️
  - name: ShareCentrePro Channel
    url: https://t.me/ShareCentrePro
    about: 想在Telegram实时跟进我们的通知？请加入这个频道！
