name: Question
description: 提出你的疑惑🤔
title: "Q: "
labels: question
body:
  - type: markdown
    attributes:
      value: |
        发表issues时，请记住：这是真的吗？有必要吗？是善良的吗？
  - type: input
    id: question
    attributes:
      label: 你的疑惑
      description: 直接的诉说出你的疑问和担忧( ͡° ͜ʖ ͡°)
      placeholder: Anything!
    validations:
      required: true
