name: Question
description: 提出你的疑惑🤔
title: "Q: "
labels: question
body:
  - type: markdown
    attributes:
      value: |
        发表issues时请记住: 这是真的吗？有必要吗？是善良的吗？
  - type: textarea
    id: repro
    attributes:
      label: 详细说明
      description: 直接的诉说出你的疑问和担忧( ͡° ͜ʖ ͡°)
      value: |
        什么: 
        怎么: 
        为什么: 
      render: bash
    validations:
      required: true
  - type: checkboxes
    id: cat-preferences
    attributes:
      label: What kinds of cats do you like?
      description: You may select more than one.
      options:
        - label: Orange cat (required. Everyone likes orange cats.)
          required: true
        - label: **Black cat**
