# your domain
domain: 128.199.181.154

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  # - source.yaml
  # use web file
  - https://raw.githubusercontent.com/yu-steven/openit/main/sub/source.yaml
