# your domain
domain: http://66.187.6.168:7777

# database url
database_url: "http://127.0.0.1"

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  # - source.yaml
  # use web file
  - https://raw.githubusercontent.com/yu-steven/openit/main/sub/source.yaml
