name: CDN
on: 
   push:
     paths:
       - 'url'
   schedule:
      - cron: "6/15 * * * *"
   workflow_dispatch:
jobs:
  job1: 
    name: long
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/git-yusteven/openit@main/long
  job2: 
    name: HTTPS
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/git-yusteven/openit@main/https
  job3: 
    name: Clash.yaml
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/git-yusteven/openit@main/Clash.yaml
  job4: 
    name: Quanx.conf
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/git-yusteven/openit@main/Quanx.conf
