name: Nodes
# 触发条件
on:
  workflow_dispatch:
jobs:
  Collecting:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装subconverter
      run: |
         wget https://github.com/yu-steven/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz -O subconverter.tar.gz&&tar -zxvf subconverter.tar.gz&&nohup ./subconverter/subconverter &
    - name: 转译
      run: |
         wget "http://0.0.0.0:25500/sub?target=clash&url=https://raw.githubusercontent.com/yu-steven/openit/main/long&config=https://raw.githubusercontent.com/yu-steven/openit/main/sub/rule.ini&emoji=true&udp=true&sort=true" -O Clash
    - name: 提交更改
      run: |
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
         git pull
         git status
         git add Clash
         git commit -m "$(date '+%Y.%m.%d %H:%M:%S')"
         git push origin main
