name: Nodes
on: 
  push:
    paths:
      - 'url'
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  my-job:
    name: Encode & Translate
    needs: bf-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 配置git
      run: git config --local user.email "actions@github.com"&&git config --local user.name "GitHub Actions"
    - name: subconverter
      run: |
         ./utils/subconverter/subconverter -g
         mv ./utils/subconverter/long ./long
         mv ./utils/subconverter/Clash.yaml ./Clash.yaml
         mv ./utils/subconverter/pool.yaml ./utils/pool/pool.yaml
         rm ./utils/pool/pool.yaml
         ./.github/url.sh > ./1
         base64 -d long | tee 2 url
         cat 1 2 > 3 && rm 1 2
         base64 3 > https -w 0 && rm 3
    - name: 提交更改
      run: ./.github/update-repo.sh || echo -e "\033[43;30m Warning：git push Failed \033[0m"
  long:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/long
  HTTPS:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/https
  Clash:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
    - name: CDN
      run: curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Clash.yaml
  Quanx:
   needs: my-job
   runs-on: ubuntu-latest
   steps:
   - name: CDN
     run: sleep 0.01 #curl https://purge.jsdelivr.net/gh/yu-steven/openit@main/Quanx.conf
