name: 节点池
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    watch:
      types: started
    repository_dispatch:
      types: Aggregate
jobs:
  Aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requests'
        run: |
          pip install -r requirements.txt
      - name: config git
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
        run: |
          git config --global user.name "$username"
          git config --global user.email "$email"
      - name: 获取订阅
        run: |
          python3 get_clash.py
      - name: upload to GitHub
        run: |
          git pull
          chmod +x ./update-repo.sh&&./update-repo.sh
