name: Reuse
on: 
  push:
    paths:
      - 'url'
  workflow_dispatch:
jobs:
  bf-job:
    name: Reuse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 配置git
      run: |
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
    - name: 写入文件
      run: |
         sed -i '/^$/d' url
         base64 url > pool -w 0
         mv ./pool ./utils/pool/pool
    - name: 提交更改
      run: ./.github/update-repo.sh
